# Generated by Django 4.2.7 on 2023-12-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
